'use strict';
const $=id=>document.getElementById(id), money=new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP',maximumFractionDigits:2}), num=new Intl.NumberFormat('en-GB',{maximumFractionDigits:2});
const fmt=v=>v==null?'—':num.format(v), gbp=v=>v==null?'—':money.format(v), pct=v=>v==null?'—':`${fmt(v*100)}%`, esc=v=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let data={},page=0;
function table(id,rows,cols){$(id).innerHTML=rows.length?`<div class="table-wrap"><table><thead><tr>${cols.map(c=>`<th>${esc(c[0])}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${cols.map(c=>`<td>${esc((c[2]||((x)=>x))(r[c[1]]))}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:'<p class="note">No qualifying results for this selection.</p>';}
function chart(id,traces,x='',y=''){if(!window.Plotly){$(id).textContent='Chart library unavailable. Tables remain available.';return;}Plotly.react(id,traces,{margin:{t:30,r:25,b:65,l:75},paper_bgcolor:'transparent',plot_bgcolor:'transparent',font:{family:'Segoe UI, sans-serif',color:'#53657a'},xaxis:{title:x,automargin:true},yaxis:{title:y,automargin:true,gridcolor:'#edf1f5'},showlegend:false},{responsive:true,displayModeBar:false});}
const cols=[['Customer','CustomerID'],['SKU','StockCode'],['Description','Description'],['Customer Segment','segment'],['Orders','orders',fmt],['Quantity','quantity',fmt],['Effective Price','price',gbp],['Latest Price','latest_price',gbp],['SKU Median Price','benchmark',gbp],['Price Gap %','gap',pct],['Volume Position','volume_position'],['Pricing Review Status','review_status'],['Reason','reason']];
function matrix(){
  const q=$('search').value.toLowerCase();
  const rows=data.pricing_opportunities.filter(r=>(!$('segment').value||r.segment===$('segment').value)&&(!$('recommendation').value||r.review_status===$('recommendation').value)&&(!$('scope').value||r.StockCode===$('sku').value)&&[r.CustomerID,r.StockCode,r.Description].join(' ').toLowerCase().includes(q));
  rows.sort((a,b)=>($('sort').value==='desc'?-1:1)*(a.gap-b.gap));
  page=Math.min(page,Math.max(0,Math.ceil(rows.length/25)-1));
  table('opportunities',rows.slice(page*25,page*25+25).map(r=>({...r,volume_position:`${r.volume_position} (${fmt(r.sku_median_quantity)} units)`})),cols);
  $('page').textContent=`${rows.length?page+1:0} / ${Math.ceil(rows.length/25)} | ${fmt(rows.length)} results`;
  $('prev').disabled=page===0;$('next').disabled=(page+1)*25>=rows.length;
}
function products(){const sku=$('sku').value,s=data.sku_pricing.find(r=>r.StockCode===sku),rows=data.pricing_opportunities.filter(r=>r.StockCode===sku&&(!$('segment').value||r.segment===$('segment').value));table('skuStats',s?[s]:[],[['SKU','StockCode'],['Description','Description'],['Customers','customers',fmt],['Minimum','minimum',gbp],['Benchmark','benchmark',gbp],['Maximum','maximum',gbp],['Spread','spread',pct],['Revenue','revenue',gbp]]);chart('priceChart',[{type:'scatter',mode:'markers',x:rows.map(r=>r.CustomerID),y:rows.map(r=>r.price),text:rows.map(r=>r.review_status),marker:{color:rows.map(r=>r.review_status==='Pricing Review'?'#c17b35':r.review_status==='Possible Volume Justification'?'#63778e':'#168b80')},hovertemplate:'%{x}<br>£%{y:.2f}<br>%{text}<extra></extra>'},...(s?[{type:'scatter',mode:'lines',x:rows.map(r=>r.CustomerID),y:rows.map(()=>s.benchmark),line:{dash:'dot',color:'#63778e'},hovertemplate:'Benchmark £%{y:.2f}<extra></extra>'}]:[])],'Customer alias','Effective price (GBP)');chart('volumeChart',[{type:'scatter',mode:'markers',x:rows.map(r=>r.quantity),y:rows.map(r=>r.price),text:rows.map(r=>`${r.CustomerID} · ${r.segment} · ${gbp(r.revenue)}`),marker:{size:rows.map(r=>r.revenue),sizemode:'area',sizeref:2*Math.max(1,...rows.map(r=>r.revenue))/(40**2),sizemin:5,color:'#168b80',opacity:.65},hovertemplate:'%{text}<br>%{x} units · £%{y:.2f}<extra></extra>'}],'Customer purchase volume','Effective price (GBP)');matrix();}
function segments(){let rows=['Small','Medium','Large','Strategic'].filter(s=>!$('segment').value||s===$('segment').value).map(segment=>{const c=data.customer_summary.filter(r=>r.segment===segment),sum=k=>c.reduce((a,r)=>a+r[k],0),orders=sum('orders');return {segment,customers:c.length,revenue:sum('revenue'),aov:orders?sum('revenue')/orders:null,units:orders?sum('quantity')/orders:null};});chart('segmentChart',[{type:'bar',x:rows.map(r=>r.segment),y:rows.map(r=>r.revenue),marker:{color:'#168b80'},hovertemplate:'%{x}<br>£%{y:,.2f}<extra></extra>'}],'','Revenue (GBP)');table('segmentTable',rows,[['Segment','segment'],['Customers','customers',fmt],['Revenue','revenue',gbp],['Average order value','aov',gbp],['Units per order','units',fmt]]);products();}
function models(){const m=data.elasticity.find(r=>r.StockCode===$('model').value);table('modelStats',m?[m]:[],[['SKU','StockCode'],['Coefficient','beta',fmt],['p-value','pvalue',v=>v.toPrecision(3)],['R²','r2',fmt],['Months','n',fmt],['Interpretation','interpretation']]);chart('elasticityChart',m?[{type:'scatter',mode:'markers',x:m.points.map(r=>r.price),y:m.points.map(r=>r.quantity),text:m.points.map(r=>r.month),marker:{color:'#168b80'}}]:[],'Monthly effective price (GBP)','Monthly quantity');const s=data.scenario.filter(r=>r.StockCode===$('model').value);table('scenarioTable',s,[['Price change','change',pct],['Price','price',gbp],['Hypothetical quantity','quantity',fmt],['Hypothetical revenue','revenue',gbp],['Difference from historical baseline','impact',gbp]]);chart('scenarioChart',[{type:'bar',x:s.map(r=>pct(r.change)),y:s.map(r=>r.revenue),marker:{color:s.map(r=>r.change===0?'#8191a6':'#168b80')}}],'Price scenario','Hypothetical historical revenue (GBP)');}
async function init(){try{const names=['metadata','customer_summary','sku_pricing','pricing_opportunities','elasticity','scenario'];await Promise.all(names.map(async n=>{let r;if('DecompressionStream' in window){r=await fetch(`data/${n}.json.gz`);if(r.ok){data[n]=unpack(await new Response(r.body.pipeThrough(new DecompressionStream('gzip'))).json());return;}}r=await fetch(`data/${n}.json`);if(!r.ok)throw Error(`${n}: HTTP ${r.status}`);data[n]=unpack(await r.json());}));const m=data.metadata;if(m.status!=='ready'){$('status').textContent='Awaiting analysis export. Run the notebook export cell with your cleaned df. No portfolio results have been invented.';return;}$('status').textContent=`${m.date_start} – ${m.date_end} · ${fmt(m.rows)} cleaned transaction lines · ${fmt(m.missing_customer_rows)} rows without customer identity`;const k=[['Total Identified Revenue',gbp(m.identified_revenue),'Identified customer accounts only'],['Customers',fmt(m.customers),'Descriptive purchasing-account proxy'],['SKUs',fmt(m.skus),'Identified-customer scope'],['Customer-SKU Relationships Reviewed',fmt(m.relationships_reviewed),'Includes insufficient-evidence cases'],['Pricing Review Cases',fmt(m.pricing_review_cases),'Below benchmark without obvious volume justification']];$('screening-note').textContent=`The ${pct(m.gap_threshold)} price-gap threshold is a configurable screening choice, not an economically proven optimal threshold. Volume position compares total customer-SKU quantity with the SKU customer median. Review commercial terms before changing price.`;$('kpis').innerHTML=k.map(r=>`<div class="card">${esc(r[0])}<strong>${esc(r[1])}</strong><span>${esc(r[2])}</span></div>`).join('');$('sku').innerHTML=data.sku_pricing.filter(r=>r.eligible).sort((a,b)=>b.revenue-a.revenue).map(r=>`<option value="${esc(r.StockCode)}">${esc(r.StockCode)} · ${esc(r.Description)}</option>`).join('');$('model').innerHTML=data.elasticity.filter(r=>r.eligible).map(r=>`<option value="${esc(r.StockCode)}">${esc(r.StockCode)}</option>`).join('')||'<option>No eligible models</option>';segments();models();}catch(e){$('status').textContent=`Analysis could not be loaded: ${e.message}. Serve this folder over HTTP (GitHub Pages or a local static preview).`;}}
['search','recommendation','scope','sort'].forEach(id=>$(id).addEventListener('input',()=>{if(!data.metadata||data.metadata.status!=='ready')return;page=0;matrix();}));$('segment').onchange=()=>{if(data.metadata?.status==='ready'){page=0;segments();}};$('sku').onchange=()=>{if(data.metadata?.status==='ready'){page=0;products();}};$('model').onchange=()=>{if(data.metadata?.status==='ready')models();};$('prev').onclick=()=>{if(page>0){page--;matrix();}};$('next').onclick=()=>{if(data.metadata?.status==='ready'){page++;matrix();}};init();

function unpack(v){if(!v.columns)return v;return v.rows.map(row=>Object.fromEntries(v.columns.map((col,i)=>[col,v.dictionaries[i]&&row[i]!=null?v.dictionaries[i][row[i]]:row[i]])));}
